# Generated by Django 3.1.4 on 2021-01-10 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ManyToManyField(default=None, related_name='watchlistUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
