# Generated by Django 3.1.4 on 2021-01-10 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210110_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auction',
            field=models.ManyToManyField(blank=True, related_name='watchlistAuction', to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='watchlistUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
