# Generated by Django 3.1.4 on 2021-01-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210110_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listing_id',
            field=models.IntegerField(null=True),
        ),
    ]
