# Generated by Django 3.1.4 on 2021-01-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210111_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedAuctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_id', models.IntegerField(null=True)),
                ('listing_id', models.IntegerField(null=True)),
            ],
        ),
    ]
