# Generated by Django 3.1.4 on 2021-01-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_closedauctions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedauctions',
            old_name='listing_id',
            new_name='winning_price',
        ),
        migrations.AddField(
            model_name='closedauctions',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='closedauctions',
            name='listing_title',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='closedauctions',
            name='winning_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
