# Generated by Django 3.1.4 on 2021-01-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_closedauctions_winner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedauctions',
            old_name='winner_name',
            new_name='winner_username',
        ),
    ]
