# Generated by Django 3.1.4 on 2021-01-13 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210112_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.auctionlisting'),
        ),
    ]
