# Generated by Django 3.1.4 on 2021-01-13 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210113_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='user_watchlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
