# Generated by Django 3.1.4 on 2021-01-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_watchlist_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedauctions',
            name='winner_id',
        ),
        migrations.RemoveField(
            model_name='closedauctions',
            name='winner_username',
        ),
    ]
