# Generated by Django 3.1.4 on 2021-01-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_closedauctions_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
    ]
