# Generated by Django 3.1.4 on 2021-01-13 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210113_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='auction_bid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auction_bid', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user_bid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
