# Generated by Django 3.1.4 on 2021-01-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210114_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedauctions',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='closedauctions',
            name='listing_title',
        ),
    ]
